//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JinStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public System.Guid Id { get; set; }
        public string TicketID { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public string departureTime { get; set; }
        public string arrivalTime { get; set; }
        public Nullable<decimal> saleTotal { get; set; }
        public string carrier { get; set; }
        public string number { get; set; }
        public Nullable<int> NumStops { get; set; }
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string CreditCardNumber { get; set; }
        public string CreditCardName { get; set; }
        public string CVV { get; set; }
        public string BillingStreet1 { get; set; }
        public string BillingStreet2 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingPostalCode { get; set; }
        public string BillingReceipient { get; set; }
        public Nullable<System.DateTime> CreditCardExpirationDate { get; set; }
        public Nullable<int> Stops { get; set; }
        public Nullable<int> CreditCardExpirationMonth { get; set; }
        public Nullable<int> CreditCardExpirationYear { get; set; }
    }
}
